### PR TITLE
Here's my attempt at fixing issue #4

### PR DESCRIPTION
**Pull request by petey**
Added two methods for coverage:
One converts the coverage data structure into something resembling lcov format,
The second converts that data structure and writes to a file. 

I also added a config option to trigger the writing of the file and the location to write to.

### CODE REVIEW

**Comment by davglass** [comment]
Once you fix all the issues I commented on, make sure you `npm i`, then `npm test` to make sure the tests are passing (that is, after you add tests for this stuff) :) Thanks!

**Comment by petey** [comment]
I hope this new patch meets your needs. Let me know if there are further updates!

**Comment by davglass** [comment]
I've merged this in, but I re-wrote a good chunk of it for better LCOV support, better report generation and just cleaned up the api. It's in master, but not published yet if you want to install it to test:

`npm -g install https://github.com/davglass/grover/tarball/master`

**Comment by petey** [comment]
Looks great. Thanks for taking the time on this. I can't wait to get this report integrated with our build process.

**Pull request closed without merging**
